
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createPage(title: string) : Promise<Result<Page, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_page", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPage(pageId: string) : Promise<Result<Page, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_page", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPages() : Promise<Result<Page[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_pages") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePage(page: Page) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_page", { page }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePage(pageId: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_page", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadBody(pageId: string) : Promise<Result<string, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_body", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveBody(pageId: string, content: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_body", { pageId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBlocks(pageId: string) : Promise<Result<Block[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_blocks", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate AI content for a note. Streams tokens back via `note-ai-stream` events.
 * 
 * The frontend sends a prompt (e.g., "expand this section", "summarize")
 * along with the page context. The response streams back incrementally.
 */
async generateNoteAi(pageId: string, prompt: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_note_ai", { pageId, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all versions for a page, ordered by timestamp descending (newest first).
 */
async getPageVersions(pageId: string) : Promise<Result<PageVersion[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_page_versions", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a specific version by ID.
 */
async getVersion(versionId: string) : Promise<Result<PageVersion, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_version", { versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a page to a specific version.
 * The current state is automatically saved as a new version before restoring.
 */
async restoreVersion(versionId: string) : Promise<Result<PageVersion, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_version", { versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compare two versions and return the diff.
 */
async compareVersions(versionAId: string, versionBId: string) : Promise<Result<LineDiff, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compare_versions", { versionAId, versionBId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compare a specific version with the current page content.
 */
async compareVersionWithCurrent(pageId: string, versionId: string) : Promise<Result<LineDiff, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compare_version_with_current", { pageId, versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a manual version snapshot.
 */
async saveManualVersion(pageId: string, description: string | null) : Promise<Result<PageVersion, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_manual_version", { pageId, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get sectioned diff for UI rendering with context folding.
 */
async getSectionedDiff(versionAId: string, versionBId: string, contextLines: number | null) : Promise<Result<[LineDiff, DiffSection[]], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sectioned_diff", { versionAId, versionBId, contextLines }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a specific version.
 */
async deleteVersion(versionId: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_version", { versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createChat(title: string | null) : Promise<Result<Chat, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_chat", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listChats() : Promise<Result<Chat[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMessages(chatId: string) : Promise<Result<Message[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_messages", { chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteChat(chatId: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_chat", { chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async submitQuery(chatId: string, query: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_query", { chatId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute a SOAR teaching stone by running its prompt through the LLM.
 * 
 * The frontend calls this when the user clicks a stone. Streams the
 * LLM response back as `chat-stream` events tagged with the chat_id.
 */
async runSoarStone(chatId: string, stonePrompt: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_soar_stone", { chatId, stonePrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel the currently running enrichment pipeline (Passes 2+3).
 * 
 * Called from the frontend abort button. Pass 1 streaming may already
 * be complete, but this ensures background enrichment stops immediately.
 */
async cancelQuery() : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_query") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGraph() : Promise<Result<GraphData, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_graph") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebuild graph from all pages — runs on spawn_blocking (CPU-bound).
 */
async rebuildGraph() : Promise<Result<GraphData, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_graph") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchGraph(query: string) : Promise<Result<GraphSearchHit[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_graph", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async extractEntities(force: boolean | null) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_entities", { force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get detailed info for a graph node including neighbors and content.
 * [MAC] — Port of NodeInspectorState.selectNode() + fetchContent().
 */
async getNodeDetails(nodeId: string) : Promise<Result<NodeDetails, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_node_details", { nodeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate an AI summary of a node's content.
 * Streams progress via `node://summary` Tauri events.
 * [MAC] — Port of NodeInspectorState.summarizeNode().
 */
async summarizeNode(nodeId: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_node", { nodeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set a node's embedding vector (e.g. after BagOfWords or ONNX inference).
 */
async setNodeEmbedding(nodeIndex: number, vector: number[]) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_node_embedding", { nodeIndex, vector }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Find K nearest semantic neighbors for a given node.
 * Returns nodes with cosine similarity >= threshold, sorted by similarity.
 * Lock ordering: graph (2) before embeddings (3) — prevents deadlock.
 */
async semanticNeighbors(nodeIndex: number, k: number, threshold: number) : Promise<Result<SemanticHit[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("semantic_neighbors", { nodeIndex, k, threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compute semantic similarity between two nodes.
 */
async semanticSimilarity(nodeA: number, nodeB: number) : Promise<Result<number, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("semantic_similarity", { nodeA, nodeB }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(name: string) : Promise<Result<Folder, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFolder(folderId: string) : Promise<Result<Folder, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folder", { folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFolders() : Promise<Result<Folder[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFolder(folder: Folder) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_folder", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFolder(folderId: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder", { folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchPages(query: string, limit: number | null) : Promise<Result<SearchResult[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_pages", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebuild the FTS5 search index from all pages + bodies.
 * Called on first launch or when the user triggers a manual re-index.
 * Runs in spawn_blocking because full reindex is O(pages) sync I/O.
 */
async rebuildSearchIndex() : Promise<Result<number, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_search_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dual-layer hybrid search: FTS5 full-text + FST graph labels, merged by score.
 * Engineering standards mandate: "FST + FTS5, single query merges both."
 */
async searchHybrid(query: string, limit: number | null) : Promise<Result<HybridSearchResult[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_hybrid", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute a structured search query with the advanced query language.
 * 
 * Query syntax:
 * - Field filters: `tag:work`, `created:>2024-01-01`, `title:"hello world"`
 * - Boolean operators: `AND`, `OR`, `NOT`
 * - Comparison: `=`, `!=`, `<`, `>`, `<=`, `>=`, `~` (contains)
 * - Grouping: `(tag:work OR tag:urgent) AND created:>2024-01-01`
 * - Tag shorthand: `#work` is equivalent to `tag:work`
 * 
 * # Examples
 * - `tag:work AND created:>2024-01-01`
 * - `(title:"Project" OR tag:urgent) AND NOT is_archived:true`
 * - `word_count:>500 AND updated:>last_week`
 */
async structuredSearch(query: string, limit: number | null) : Promise<Result<Page[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("structured_search", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a structured query without executing it.
 * Returns Ok if valid, or an error with position info.
 */
async validateQuery(query: string) : Promise<Result<null, QueryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_query", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all saved queries.
 */
async getSavedQueries() : Promise<Result<SavedQuery[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_saved_queries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a query with a name.
 */
async saveQuery(name: string, queryStr: string) : Promise<Result<SavedQuery, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_query", { name, queryStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a saved query by name.
 */
async deleteQuery(name: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_query", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute a saved query by name.
 * Increments the use count and updates last_used_at.
 */
async executeSavedQuery(name: string, limit: number | null) : Promise<Result<Page[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_saved_query", { name, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a saved query.
 */
async renameQuery(oldName: string, newName: string) : Promise<Result<SavedQuery, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_query", { oldName, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the most frequently used queries.
 */
async getPopularQueries(limit: number | null) : Promise<Result<SavedQuery[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_popular_queries", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get recently used queries.
 */
async getRecentQueries(limit: number | null) : Promise<Result<SavedQuery[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_queries", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute a structured search and return detailed results including metadata.
 */
async structuredSearchDetailed(query: string, limit: number | null) : Promise<Result<StructuredSearchResult, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("structured_search_detailed", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVaultPath() : Promise<Result<string | null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_vault_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setVaultPath(path: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_vault_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import all .md files from the user's vault directory.
 * Incremental: only imports files newer than last sync.
 * Runs on spawn_blocking to avoid starving the async runtime with sync I/O.
 */
async importVault() : Promise<Result<ImportResult, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a single page to the vault as a .md file with front-matter.
 * Runs on spawn_blocking to avoid blocking the async runtime with file I/O.
 */
async exportPage(pageId: string) : Promise<Result<string, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_page", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export all pages to the vault directory.
 * Runs on spawn_blocking to avoid blocking the async runtime with file I/O.
 */
async exportAll() : Promise<Result<number, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start watching the configured vault directory for .md changes.
 * Emits `vault-change` events on the frontend when files change.
 * Auto-imports changed files into the database.
 */
async startVaultWatcher() : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_vault_watcher") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the live vault watcher.
 */
async stopVaultWatcher() : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_vault_watcher") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if the vault watcher is currently running.
 */
async isVaultWatching() : Promise<Result<boolean, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_vault_watching") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInferenceConfig() : Promise<Result<InferenceConfig, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_inference_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setInferenceConfig(config: InferenceConfig) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_inference_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testConnection(provider: string, apiKey: string, model: string) : Promise<Result<ConnectionTestResult, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_connection", { provider, apiKey, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppInfo() : Promise<Result<JsonValue, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Probe all local AI services and return their status.
 * [NEW] — Windows equivalent of macOS Apple Intelligence availability check.
 * Enables triage routing: NPU (Foundry) → GPU (Ollama) → Cloud.
 * Also caches availability in AppState for triage routing.
 */
async checkLocalServices() : Promise<Result<LocalServiceStatus[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_local_services") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get local model configuration (Foundry + Ollama model names and URLs).
 */
async getLocalModelConfig() : Promise<Result<LocalModelConfig, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_model_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set local model configuration. Persists to settings KV for triage routing.
 */
async setLocalModelConfig(config: LocalModelConfig) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_local_model_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get today's cost summary (tokens, calls, spending, budget status).
 */
async getCostSummary() : Promise<Result<CostSummary, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cost_summary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the daily spending budget (USD). 0 = unlimited.
 */
async setDailyBudget(budgetUsd: number) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_daily_budget", { budgetUsd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset all cost tracking data for today.
 */
async resetCostTracker() : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_cost_tracker") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current embedding system status (backend type, dimension, node count).
 */
async getEmbeddingStatus() : Promise<Result<EmbeddingStatus, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_embedding_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate an embedding vector for arbitrary text using the current embedder.
 */
async embedText(text: string) : Promise<Result<number[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("embed_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Find the K most semantically similar graph nodes to a text query.
 * Embeds the query, then searches the EmbeddingStore via cosine similarity.
 * Lock ordering: graph (2) then embeddings (3).
 */
async findSimilarNodes(text: string, k: number) : Promise<Result<SimilarNode[], any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_similar_nodes", { text, k }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the physics simulation loop at the configured tick rate (default: 90Hz).
 * Loads graph from DB, builds physics world, and emits `physics-frame` events.
 */
async startPhysics() : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_physics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the physics simulation loop.
 */
async stopPhysics() : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_physics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pin a node in place (drag start).
 */
async pinNode(nodeId: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pin_node", { nodeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unpin a node (drag end).
 */
async unpinNode(nodeId: string) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unpin_node", { nodeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move a pinned node to new coordinates (during drag).
 */
async moveNode(nodeId: string, x: number, y: number, z: number) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_node", { nodeId, x, y, z }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if physics is currently running.
 */
async isPhysicsRunning() : Promise<Result<boolean, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_physics_running") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle between graph layout and FPS exploration mode.
 * Returns the new mode ("Graph" or "Fps").
 */
async toggleFpsMode() : Promise<Result<string, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_fps_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send FPS input (thruster + mouse) for the current frame.
 * Called by the frontend on each animation frame while in FPS mode.
 * Writes to a decoupled input buffer (NOT the physics mutex) to avoid
 * contention with the 90Hz physics loop. Input is consumed by the loop
 * on its next tick.
 */
async fpsInput(input: FpsInput) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fps_input", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current physics mode ("Graph" or "Fps").
 */
async getPhysicsMode() : Promise<Result<string, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_physics_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the physics target FPS (tick rate).
 * Lower values reduce CPU usage on low-end hardware.
 * Common values: 30 (low-end), 60 (mid), 90 (high-end).
 * Requires physics restart to take effect.
 */
async setPhysicsTargetFps(fps: number) : Promise<Result<null, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_physics_target_fps", { fps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start research mode on a page. Sets stage to "gathering".
 */
async startResearch(pageId: string, topic: string | null) : Promise<Result<ResearchStatus, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_research", { pageId, topic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Advance research to the next stage. Each transition runs an LLM analysis
 * pass appropriate for that stage.
 */
async advanceResearch(pageId: string) : Promise<Result<ResearchStatus, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("advance_research", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current research status for a page.
 */
async getResearchStatus(pageId: string) : Promise<Result<ResearchStatus, any>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_research_status", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Block = { id: BlockId; page_id: PageId; parent_block_id: BlockId | null; order: number; depth: number; block_type: BlockType; content: string; is_collapsed: boolean; is_checked: boolean; created_at: number; updated_at: number }
export type BlockId = string
export type BlockType = "Paragraph" | "Heading1" | "Heading2" | "Heading3" | "Code" | "Quote" | "Callout" | "BulletList" | "NumberedList" | "Todo" | "Divider" | "Toggle" | "Math"
export type Chat = { id: ChatId; title: string; chat_type: string; page_context_id: PageId | null; created_at: number; updated_at: number }
export type ChatId = string
export type ConnectionTestResult = { success: boolean; message: string; latency_ms: number | null }
/**
 * Cost summary returned to the frontend.
 */
export type CostSummary = { daily_input_tokens: number; daily_output_tokens: number; daily_call_count: number; daily_cost_usd: number; daily_budget_usd: number; budget_exceeded: boolean; provider_breakdown: ProviderCost[] }
export type DiffLineKind = { kind: "Unchanged"; content: string } | { kind: "Added"; content: string } | { kind: "Removed"; content: string } | { kind: "Modified"; content: { old: string; new: string } }
export type DiffSection = ({ kind: "Visible"; items: IndexedLine[] } | { kind: "Collapsed"; items: IndexedLine[] }) & { id: number }
export type DiffStats = { added: number; removed: number; modified: number }
/**
 * Embedding system status returned to the frontend.
 */
export type EmbeddingStatus = { backend: string; dimension: number; node_count: number; model_path: string | null }
export type Folder = { id: FolderId; name: string; emoji: string | null; sort_order: number; is_collection: boolean; parent_folder_id: FolderId | null; created_at: number }
export type FolderId = string
/**
 * Input state from the frontend, sent per frame or on keypress.
 */
export type FpsInput = { 
/**
 * Forward/backward thrust (-1.0 = backward, 1.0 = forward).
 */
forward: number; 
/**
 * Left/right strafe (-1.0 = left, 1.0 = right).
 */
strafe: number; 
/**
 * Up/down thrust (-1.0 = down, 1.0 = up).
 */
vertical: number; 
/**
 * Mouse horizontal delta (pixels).
 */
mouse_dx: number; 
/**
 * Mouse vertical delta (pixels).
 */
mouse_dy: number; 
/**
 * Whether to toggle stabilization mode this frame.
 */
toggle_stabilization: boolean }
export type GraphData = { nodes: GraphNode[]; edges: GraphEdge[] }
export type GraphEdge = { id: GraphEdgeId; source_node_id: GraphNodeId; target_node_id: GraphNodeId; edge_type: GraphEdgeType; weight: number; metadata_json: string | null; is_manual: boolean; created_at: number }
export type GraphEdgeId = string
export type GraphEdgeType = "Reference" | "Contains" | "Tagged" | "Mentions" | "Cites" | "Authored" | "Related" | "Quotes" | "Supports" | "Contradicts" | "Expands" | "Questions"
export type GraphNode = { id: GraphNodeId; node_type: GraphNodeType; label: string; source_id: string; weight: number; metadata_json: string | null; is_manual: boolean; created_at: number }
export type GraphNodeId = string
export type GraphNodeType = "Note" | "Chat" | "Idea" | "Source" | "Folder" | "Quote" | "Tag" | "Block"
/**
 * Search result with fuzzy relevance score.
 */
export type GraphSearchHit = { node_id: string; label: string; node_type: GraphNodeType; score: number }
/**
 * A unified search result from both FTS5 and FST layers.
 */
export type HybridSearchResult = { page_id: string; title: string; snippet: string; score: number; 
/**
 * "fts5" | "fst" | "both"
 */
source: string }
/**
 * Import result returned to the frontend.
 */
export type ImportResult = { imported: number; updated: number; skipped: number; errors: number }
export type IndexedLine = ({ kind: "Unchanged"; content: string } | { kind: "Added"; content: string } | { kind: "Removed"; content: string } | { kind: "Modified"; content: { old: string; new: string } }) & { index: number }
export type InferenceConfig = { api_provider: string; api_key: string; model: string; ollama_base_url: string; token_cap: number; daily_budget_cents: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LineDiff = { lines: DiffLineKind[]; stats: DiffStats }
/**
 * Configuration for local AI services (Foundry Local + Ollama).
 * These settings are used by the triage router when routing to NPU/GPU.
 */
export type LocalModelConfig = { foundry_model: string; foundry_base_url: string; ollama_model: string; ollama_base_url: string }
/**
 * Status of a local AI service (Foundry Local or Ollama).
 */
export type LocalServiceStatus = { name: string; available: boolean; endpoint: string; models: string[]; latency_ms: number | null; error: string | null }
export type Message = { id: MessageId; chat_id: ChatId; role: string; content: string; dual_message_data: string | null; truth_assessment_data: string | null; 
/**
 * Confidence score (0.0–1.0) from truth assessment. None for user messages.
 */
confidence_score: number | null; 
/**
 * Evidence grade letter: "A", "B", "C", "D", "F". None for user messages.
 */
evidence_grade: string | null; 
/**
 * Inference mode used: "research", "moderate", etc. None for user messages.
 */
inference_mode: string | null; is_streaming: boolean; created_at: number }
export type MessageId = string
/**
 * Neighbor info returned by get_node_details.
 */
export type NeighborInfo = { node_id: string; label: string; node_type: GraphNodeType; edge_type: GraphEdgeType }
/**
 * Full details for a selected node — matches macOS NodeInspectorState.
 */
export type NodeDetails = { node_id: string; label: string; node_type: GraphNodeType; source_id: string; weight: number; link_count: number; neighbors: NeighborInfo[]; 
/**
 * Page body or assembled context (truncated to 3000 chars).
 */
content_preview: string }
export type Page = { id: PageId; title: string; summary: string; emoji: string | null; research_stage: number; tags: string[]; word_count: number; is_pinned: boolean; is_archived: boolean; is_favorite: boolean; is_journal: boolean; is_locked: boolean; sort_order: number; journal_date: string | null; front_matter_data: string | null; ideas_data: string | null; needs_vault_sync: boolean; last_synced_body_hash: string | null; last_synced_at: number | null; file_path: string | null; subfolder: string | null; parent_page_id: PageId | null; folder_id: FolderId | null; template_id: string | null; created_at: number; updated_at: number }
export type PageId = string
export type PageVersion = { id: string; page_id: PageId; title: string; body: string; hash: string; parent_hash: string | null; timestamp: number; word_count: number; changes_summary: string | null }
/**
 * Per-provider cost breakdown.
 */
export type ProviderCost = { provider: string; call_count: number; cost_usd: number }
/**
 * Query parsing error
 */
export type QueryError = { message: string; position: number | null; kind: QueryErrorKind }
/**
 * Types of query errors
 */
export type QueryErrorKind = "Generic" | "UnexpectedToken" | "UnclosedQuote" | "UnclosedParen" | "InvalidOperator" | "InvalidField" | "InvalidValue" | "EmptyQuery"
export type ResearchStatus = { page_id: string; stage: number; stage_name: string; title: string }
/**
 * Saved query struct for persistence
 */
export type SavedQuery = { name: string; query: string; created_at: number; last_used_at: number | null; use_count: number }
export type SearchResult = { page_id: PageId; title: string; snippet: string; score: number }
/**
 * A semantic neighbor hit (cosine similarity above threshold).
 */
export type SemanticHit = { node_id: string; label: string; node_type: GraphNodeType; similarity: number }
/**
 * Semantic search result with node metadata.
 */
export type SimilarNode = { node_id: string; label: string; node_type: GraphNodeType; similarity: number }
/**
 * Search result from structured query execution.
 */
export type StructuredSearchResult = { pages: Page[]; total_count: number; execution_time_ms: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
