/**
 * Tauri Event Bridge — Wires Rust backend events into the Zustand store.
 *
 * The `commands` object (typed invoke wrappers) is auto-generated by
 * tauri-specta at `@/lib/bindings`. This module handles the OTHER half:
 * subscribing to Tauri events emitted by the Rust backend and dispatching
 * them into the correct Zustand slices.
 *
 * Call `setupTauriListeners()` once at app startup (in main.tsx).
 * Returns an `unlisten` function for cleanup.
 */

import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import { usePFCStore } from '@/lib/store/use-pfc-store';

// ── Event payload types (matches Rust serialization) ───────────────

interface StreamChunk {
  chat_id: string;
  text: string;
  done: boolean;
}

interface PipelineStageEvent {
  chat_id: string;
  stage: string;
  status: string;
  detail: string;
}

interface SignalPayload {
  confidence: number;
  entropy: number;
  dissonance: number;
  health_score: number;
  safety_state?: string;
  risk_score?: number;
  focus_depth?: number;
  temperature_scale?: number;
  concepts?: string[];
  grade?: string;
  mode?: string;
}

interface PhysicsFrame {
  positions: Array<{ id: string; x: number; y: number; z: number }>;
  settled: boolean;
}

interface FpsFrame {
  x: number;
  y: number;
  z: number;
  yaw: number;
  pitch: number;
  speed: number;
  proximity_node: { node_id: string; distance: number } | null;
  stabilization: string;
}

interface ExtractionProgress {
  phase: string;
  current: number;
  total: number;
}

// ── Rust → TypeScript enrichment mapping ─────────────────────────

/** Raw payload shape from Rust (snake_case, mirrors EnrichedData) */
interface EnrichedPayload {
  dual_message: {
    raw_analysis: string;
    epistemic_tags: { data: number; model: number; uncertain: number; conflict: number };
    layman_summary?: {
      what_was_tried: { label: string; content: string };
      what_is_likely_true: { label: string; content: string };
      confidence_explanation: { label: string; content: string };
      what_could_change: { label: string; content: string };
      who_should_trust: { label: string; content: string };
    };
    reflection?: {
      self_critical_questions: string[];
      adjustments: string[];
      least_defensible_claim: string;
      precision_vs_evidence_check: string;
    };
    arbitration?: {
      consensus: boolean;
      votes: Array<{ engine: string; position: string; reasoning: string; confidence: number }>;
      disagreements: string[];
      resolution: string;
    };
  };
  truth_assessment: {
    signal_interpretation: string;
    overall_truth_likelihood: number;
    weaknesses: string[];
    improvements: string[];
    blind_spots: string[];
    confidence_calibration: string;
    data_vs_model_balance: string;
    recommended_actions: string[];
  };
}

import type { DualMessage, TruthAssessment, LaymanSummary, ReflectionResult, ArbitrationResult } from '@/lib/types';

function mapDualMessage(raw: EnrichedPayload['dual_message']): DualMessage {
  const tags = raw.epistemic_tags;

  // Build inline uncertainty tags from raw analysis text
  const uncertaintyTags: Array<{ tag: string; claim: string }> = [];
  for (const tagName of ['DATA', 'MODEL', 'UNCERTAIN', 'CONFLICT'] as const) {
    const count = tags[tagName.toLowerCase() as keyof typeof tags];
    for (let i = 0; i < count; i++) {
      uncertaintyTags.push({ tag: tagName, claim: '' });
    }
  }

  let laymanSummary: LaymanSummary | undefined;
  if (raw.layman_summary) {
    const ls = raw.layman_summary;
    laymanSummary = {
      whatWasTried: ls.what_was_tried.content,
      whatIsLikelyTrue: ls.what_is_likely_true.content,
      confidenceExplanation: ls.confidence_explanation.content,
      whatCouldChange: ls.what_could_change.content,
      whoShouldTrust: ls.who_should_trust.content,
      sectionLabels: {
        whatWasTried: ls.what_was_tried.label,
        whatIsLikelyTrue: ls.what_is_likely_true.label,
        confidenceExplanation: ls.confidence_explanation.label,
        whatCouldChange: ls.what_could_change.label,
        whoShouldTrust: ls.who_should_trust.label,
      },
    };
  }

  let reflection: ReflectionResult | undefined;
  if (raw.reflection) {
    reflection = {
      selfCriticalQuestions: raw.reflection.self_critical_questions,
      adjustments: raw.reflection.adjustments,
      leastDefensibleClaim: raw.reflection.least_defensible_claim,
      precisionVsEvidenceCheck: raw.reflection.precision_vs_evidence_check,
    };
  }

  let arbitration: ArbitrationResult | undefined;
  if (raw.arbitration) {
    arbitration = {
      consensus: raw.arbitration.consensus,
      votes: raw.arbitration.votes.map((v) => ({
        engine: v.engine,
        position: v.position as 'supports' | 'opposes' | 'neutral',
        reasoning: v.reasoning,
        confidence: v.confidence,
      })),
      disagreements: raw.arbitration.disagreements,
      resolution: raw.arbitration.resolution,
    };
  }

  return {
    rawAnalysis: raw.raw_analysis,
    epistemicTags: tags,
    laymanSummary,
    reflection,
    arbitration,
    uncertaintyTags,
  };
}

function mapTruthAssessment(raw: EnrichedPayload['truth_assessment']): TruthAssessment {
  return {
    signalInterpretation: raw.signal_interpretation,
    overallTruthLikelihood: raw.overall_truth_likelihood,
    weaknesses: raw.weaknesses,
    improvements: raw.improvements,
    blindSpots: raw.blind_spots,
    confidenceCalibration: raw.confidence_calibration,
    dataVsModelBalance: raw.data_vs_model_balance,
    recommendedActions: raw.recommended_actions,
  };
}

// ── Listener Setup ────────────────────────────────────────────────

export async function setupTauriListeners(): Promise<UnlistenFn> {
  const unlisteners: UnlistenFn[] = [];

  // ── Chat streaming (Pass 1 text deltas) ──
  unlisteners.push(
    await listen<StreamChunk>('chat-stream', (event) => {
      const store = usePFCStore.getState();
      const { text, done } = event.payload;

      if (done) {
        store.stopStreaming();
      } else if (text) {
        store.appendStreamingText(text);
      }
    })
  );

  // ── Pipeline stage progress ──
  // Uses advanceStage() from pipeline slice
  unlisteners.push(
    await listen<PipelineStageEvent>('pipeline://stage', (event) => {
      const { stage, status } = event.payload;
      const store = usePFCStore.getState();
      const stageStatus = (status === 'Completed' || status === 'completed')
        ? 'complete' as const
        : 'active' as const;
      store.advanceStage(stage as never, { status: stageStatus });
    })
  );

  // ── Signal updates ──
  // Uses applySignalUpdate() which handles all signal fields
  unlisteners.push(
    await listen<SignalPayload>('pipeline://signals', (event) => {
      const s = event.payload;
      usePFCStore.getState().applySignalUpdate({
        confidence: s.confidence,
        entropy: s.entropy,
        dissonance: s.dissonance,
        healthScore: s.health_score,
        riskScore: s.risk_score,
        focusDepth: s.focus_depth,
        temperatureScale: s.temperature_scale,
        activeConcepts: s.concepts,
      });
    })
  );

  // ── Deliberation (thinking tokens) ──
  // Uses appendReasoningText() from message slice
  unlisteners.push(
    await listen<StreamChunk>('pipeline://deliberation', (event) => {
      if (event.payload.text) {
        usePFCStore.getState().appendReasoningText(event.payload.text);
      }
    })
  );

  // ── Concepts extracted ──
  // Uses updateConcepts() from pipeline slice (concepts, chord=1, harmony=0)
  unlisteners.push(
    await listen<string[]>('pipeline://concepts', (event) => {
      usePFCStore.getState().updateConcepts(event.payload, 1, 0);
    })
  );

  // ── Enrichment complete (Pass 2+3 results) ──
  unlisteners.push(
    await listen<EnrichedPayload>('pipeline://enriched', (event) => {
      const store = usePFCStore.getState();
      const data = event.payload;

      // Map Rust snake_case to our camelCase types
      const dualMessage = mapDualMessage(data.dual_message);
      const truthAssessment = mapTruthAssessment(data.truth_assessment);
      const confidence = truthAssessment.overallTruthLikelihood;

      // Derive evidence grade from confidence
      const grade = confidence >= 0.8 ? 'A'
        : confidence >= 0.65 ? 'B'
        : confidence >= 0.5 ? 'C'
        : confidence >= 0.3 ? 'D'
        : 'F';

      store.completeProcessing(dualMessage, confidence, grade, 'research', truthAssessment);
    })
  );

  // ── Pipeline errors ──
  unlisteners.push(
    await listen<string>('pipeline://error', (event) => {
      usePFCStore.getState().addToast({
        message: event.payload,
        type: 'error',
      });
    })
  );

  // ── Physics frame (graph positions at 90Hz) ──
  // Graph renderer will consume this when Bevy/wgpu surface is integrated.
  unlisteners.push(
    await listen<PhysicsFrame>('physics-frame', (_event) => {
      // TODO: feed positions into graph canvas component
    })
  );

  // ── FPS exploration mode frame (player HUD data) ──
  unlisteners.push(
    await listen<FpsFrame>('fps-frame', (_event) => {
      // TODO: update FPS HUD (speedometer, proximity label, stabilization indicator)
    })
  );

  // ── SOAR events (teaching stones, probe results) ──
  unlisteners.push(
    await listen<unknown>('pipeline://soar', (event) => {
      const store = usePFCStore.getState();
      const data = event.payload as Record<string, unknown>;

      // ProbeComplete — notify user if at learning edge
      if (data.ProbeComplete) {
        const probe = data.ProbeComplete as { at_edge: boolean; reason?: string };
        if (probe.at_edge) {
          store.addToast({ message: 'SOAR: Knowledge edge detected — teaching stones available', type: 'info' });
        }
      }

      // StonePresented — could be rendered in a dedicated SOAR panel
      if (data.StonePresented) {
        const stone = data.StonePresented as { index: number; stone: { name: string } };
        store.addToast({ message: `SOAR Stone ${stone.index + 1}: ${stone.stone.name}`, type: 'info' });
      }
    })
  );

  // ── Chat title update (auto-generated from first exchange) ──
  unlisteners.push(
    await listen<{ chat_id: string; title: string }>('chat-title-update', (event) => {
      const store = usePFCStore.getState();
      const { chat_id, title } = event.payload;
      // Update thread title in the store if the method exists
      if ('updateThreadTitle' in store && typeof store.updateThreadTitle === 'function') {
        (store as Record<string, unknown> & { updateThreadTitle: (id: string, t: string) => void }).updateThreadTitle(chat_id, title);
      }
    })
  );

  // ── Chat stream replace (vault actions stripped from response) ──
  unlisteners.push(
    await listen<StreamChunk>('chat-stream-replace', (event) => {
      const store = usePFCStore.getState();
      if (event.payload.text) {
        store.clearStreamingText();
        store.appendStreamingText(event.payload.text);
      }
    })
  );

  // ── Note AI streaming (from generate_note_ai command) ──
  unlisteners.push(
    await listen<{ page_id: string; text: string; done: boolean; error?: boolean }>(
      'note-ai-stream',
      (event) => {
        const store = usePFCStore.getState();
        const { text, done, error } = event.payload;
        if (error) {
          store.addToast({ message: text, type: 'error' });
        }
        if (done) {
          store.stopNoteAIGeneration();
        } else if (text) {
          store.appendNoteAIText(text);
        }
      }
    )
  );

  // ── Entity extraction progress ──
  unlisteners.push(
    await listen<ExtractionProgress>('extraction://progress', (event) => {
      const { phase, current, total } = event.payload;
      usePFCStore.getState().addToast({
        message: `${phase}: ${current}/${total}`,
        type: 'info',
      });
    })
  );

  // Return combined cleanup function
  return () => {
    for (const unlisten of unlisteners) {
      unlisten();
    }
  };
}
