/**
 * Tauri Event Bridge — Wires Rust backend events into the Zustand store.
 *
 * The `commands` object (typed invoke wrappers) is auto-generated by
 * tauri-specta at `@/lib/bindings`. This module handles the OTHER half:
 * subscribing to Tauri events emitted by the Rust backend and dispatching
 * them into the correct Zustand slices.
 *
 * Call `setupTauriListeners()` once at app startup (in main.tsx).
 * Returns an `unlisten` function for cleanup.
 */

import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import { usePFCStore } from '@/lib/store/use-pfc-store';

// ── Event payload types (matches Rust serialization) ───────────────

interface StreamChunk {
  chat_id: string;
  text: string;
  done: boolean;
}

interface PipelineStageEvent {
  chat_id: string;
  stage: string;
  status: string;
  detail: string;
}

interface SignalPayload {
  confidence: number;
  entropy: number;
  dissonance: number;
  health_score: number;
  safety_state?: string;
  risk_score?: number;
  focus_depth?: number;
  temperature_scale?: number;
  concepts?: string[];
  grade?: string;
  mode?: string;
}

interface PhysicsFrame {
  positions: Array<{ id: string; x: number; y: number; z: number }>;
  settled: boolean;
}

interface FpsFrame {
  x: number;
  y: number;
  z: number;
  yaw: number;
  pitch: number;
  speed: number;
  proximity_node: { node_id: string; distance: number } | null;
  stabilization: string;
}

interface ExtractionProgress {
  phase: string;
  current: number;
  total: number;
}

// ── Listener Setup ────────────────────────────────────────────────

export async function setupTauriListeners(): Promise<UnlistenFn> {
  const unlisteners: UnlistenFn[] = [];

  // ── Chat streaming (Pass 1 text deltas) ──
  unlisteners.push(
    await listen<StreamChunk>('chat-stream', (event) => {
      const store = usePFCStore.getState();
      const { text, done } = event.payload;

      if (done) {
        store.stopStreaming();
      } else if (text) {
        store.appendStreamingText(text);
      }
    })
  );

  // ── Pipeline stage progress ──
  // Uses advanceStage() from pipeline slice
  unlisteners.push(
    await listen<PipelineStageEvent>('pipeline://stage', (event) => {
      const { stage, status } = event.payload;
      const store = usePFCStore.getState();
      const stageStatus = (status === 'Completed' || status === 'completed')
        ? 'complete' as const
        : 'active' as const;
      store.advanceStage(stage as never, { status: stageStatus });
    })
  );

  // ── Signal updates ──
  // Uses applySignalUpdate() which handles all signal fields
  unlisteners.push(
    await listen<SignalPayload>('pipeline://signals', (event) => {
      const s = event.payload;
      usePFCStore.getState().applySignalUpdate({
        confidence: s.confidence,
        entropy: s.entropy,
        dissonance: s.dissonance,
        healthScore: s.health_score,
        riskScore: s.risk_score,
        focusDepth: s.focus_depth,
        temperatureScale: s.temperature_scale,
        activeConcepts: s.concepts,
      });
    })
  );

  // ── Deliberation (thinking tokens) ──
  // Uses appendReasoningText() from message slice
  unlisteners.push(
    await listen<StreamChunk>('pipeline://deliberation', (event) => {
      if (event.payload.text) {
        usePFCStore.getState().appendReasoningText(event.payload.text);
      }
    })
  );

  // ── Concepts extracted ──
  // Uses updateConcepts() from pipeline slice (concepts, chord=1, harmony=0)
  unlisteners.push(
    await listen<string[]>('pipeline://concepts', (event) => {
      usePFCStore.getState().updateConcepts(event.payload, 1, 0);
    })
  );

  // ── Enrichment complete (Pass 2+3 results) ──
  // Enrichment data is persisted to DB by Rust. This event signals the
  // UI to refresh — full parsing will be added when the enrichment panel
  // component is wired up.
  unlisteners.push(
    await listen<unknown>('pipeline://enriched', (_event) => {
      // TODO: parse enrichment payload and call finalizeMessage()
      // with dualMessage, truthAssessment, confidence, grade, mode.
    })
  );

  // ── Pipeline errors ──
  unlisteners.push(
    await listen<string>('pipeline://error', (event) => {
      usePFCStore.getState().addToast({
        message: event.payload,
        type: 'error',
      });
    })
  );

  // ── Physics frame (graph positions at 90Hz) ──
  // Graph renderer will consume this when Bevy/wgpu surface is integrated.
  unlisteners.push(
    await listen<PhysicsFrame>('physics-frame', (_event) => {
      // TODO: feed positions into graph canvas component
    })
  );

  // ── FPS exploration mode frame (player HUD data) ──
  unlisteners.push(
    await listen<FpsFrame>('fps-frame', (_event) => {
      // TODO: update FPS HUD (speedometer, proximity label, stabilization indicator)
    })
  );

  // ── Entity extraction progress ──
  unlisteners.push(
    await listen<ExtractionProgress>('extraction://progress', (event) => {
      const { phase, current, total } = event.payload;
      usePFCStore.getState().addToast({
        message: `${phase}: ${current}/${total}`,
        type: 'info',
      });
    })
  );

  // Return combined cleanup function
  return () => {
    for (const unlisten of unlisteners) {
      unlisten();
    }
  };
}
