/**
 * UI Display Types — thin type definitions for rendering data from Rust backend.
 *
 * These will eventually be auto-generated by tauri-specta from Rust structs.
 * For now they're minimal placeholders so the UI compiles.
 * ALL logic lives in Rust crates (ported from Mac version). TypeScript only renders.
 */

import type { PipelineStage, SafetyState } from '@/lib/constants';

// ── Pipeline Display ─────────────────────────────────────────────

export type StageStatus = 'idle' | 'active' | 'complete' | 'error';

export interface StageResult {
  stage: PipelineStage;
  status: StageStatus;
  summary: string;
  detail?: string;
  value?: number;
}

export interface TDASnapshot {
  betti0: number;
  betti1: number;
  persistenceEntropy: number;
  maxPersistence: number;
}

export interface SignalUpdate {
  confidence?: number;
  entropy?: number;
  dissonance?: number;
  healthScore?: number;
  safetyState?: SafetyState;
  riskScore?: number;
  tda?: Partial<TDASnapshot>;
  focusDepth?: number;
  temperatureScale?: number;
  activeConcepts?: string[];
  activeChordProduct?: number;
  harmonyKeyDistance?: number;
}

// ── Messages ─────────────────────────────────────────────────────

export type AnalysisMode = 'research' | 'quick' | 'deep';
export type EvidenceGrade = 'A' | 'B' | 'C' | 'D' | 'F' | 'N/A';

export interface SummarySection {
  label: string;
  content: string;
}

export interface LaymanSummary {
  whatWasTried: string;
  whatIsLikelyTrue: string;
  confidenceExplanation: string;
  whatCouldChange: string;
  whoShouldTrust: string;
  /** Adaptive section labels from the query type */
  sectionLabels?: Record<string, string>;
}

export interface EpistemicTagCounts {
  data: number;
  model: number;
  uncertain: number;
  conflict: number;
}

export interface ReflectionResult {
  selfCriticalQuestions: string[];
  adjustments: string[];
  leastDefensibleClaim: string;
  precisionVsEvidenceCheck: string;
}

export interface ArbitrationVote {
  engine: string;
  position: 'supports' | 'opposes' | 'neutral';
  reasoning: string;
  confidence: number;
}

export interface ArbitrationResult {
  consensus: boolean;
  votes: ArbitrationVote[];
  disagreements: string[];
  resolution: string;
}

export interface DualMessage {
  rawAnalysis: string;
  epistemicTags: EpistemicTagCounts;
  laymanSummary?: LaymanSummary;
  reflection?: ReflectionResult;
  arbitration?: ArbitrationResult;
  /** Derived tag list for inline rendering */
  uncertaintyTags: Array<{ tag: string; claim: string }>;
  /** Model vs. data tension flags from consolidated enrichment */
  modelVsDataFlags?: Array<{ source: string; claim: string }>;
}

export interface TruthAssessment {
  signalInterpretation: string;
  overallTruthLikelihood: number;
  weaknesses: string[];
  improvements: string[];
  blindSpots: string[];
  confidenceCalibration: string;
  dataVsModelBalance: string;
  recommendedActions: string[];
}

export interface FileAttachment {
  id: string;
  name: string;
  type: string;
  uri: string;
  size: number;
  mimeType?: string;
  /** Data URL preview for images */
  preview?: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'system';
  text: string;
  timestamp: number;
  confidence?: number;
  evidenceGrade?: EvidenceGrade;
  mode?: AnalysisMode;
  dualMessage?: DualMessage;
  truthAssessment?: TruthAssessment;
  concepts?: string[];
  reasoning?: { content: string; duration?: number };
  attachments?: FileAttachment[];
}

// ── Pipeline Controls (UI sliders) ───────────────────────────────

export interface PipelineControls {
  focusDepthOverride: number | null;
  temperatureOverride: number | null;
  complexityBias: number;
  adversarialIntensity: number;
  bayesianPriorStrength: number;
}

// ── Inference Config (settings UI) ───────────────────────────────

export type InferenceMode = 'api' | 'local';
export type ApiProvider = 'openai' | 'anthropic' | 'google';

export type OpenAIModel = 'gpt-4o' | 'gpt-4o-mini' | 'o1' | 'o1-mini' | 'o3-mini';
export type AnthropicModel = 'claude-sonnet-4-20250514' | 'claude-opus-4-20250514' | 'claude-haiku-3-20250401';
export type GoogleModel = 'gemini-2.5-flash' | 'gemini-2.5-pro' | 'gemini-2.0-flash';

export interface InferenceConfig {
  mode: InferenceMode;
  apiProvider?: ApiProvider;
  apiKey?: string;
  openaiModel?: OpenAIModel;
  anthropicModel?: AnthropicModel;
  googleModel?: GoogleModel;
  ollamaBaseUrl?: string;
  ollamaModel?: string;
}

export interface OllamaHardwareStatus {
  gpuAvailable: boolean;
  gpuName?: string;
  vramMB?: number;
  systemMemoryMB?: number;
}

// ── Provider/Model lists for settings dropdowns ──────────────────

export const API_PROVIDERS: { id: ApiProvider; label: string; value: ApiProvider; color: string }[] = [
  { id: 'openai', label: 'OpenAI', value: 'openai', color: '#10A37F' },
  { id: 'anthropic', label: 'Anthropic', value: 'anthropic', color: '#D4A574' },
  { id: 'google', label: 'Google', value: 'google', color: '#4285F4' },
];

export const OPENAI_MODELS: { id: OpenAIModel; label: string; value: OpenAIModel }[] = [
  { id: 'gpt-4o', label: 'GPT-4o', value: 'gpt-4o' },
  { id: 'gpt-4o-mini', label: 'GPT-4o Mini', value: 'gpt-4o-mini' },
  { id: 'o1', label: 'o1', value: 'o1' },
  { id: 'o1-mini', label: 'o1 Mini', value: 'o1-mini' },
  { id: 'o3-mini', label: 'o3 Mini', value: 'o3-mini' },
];

export const ANTHROPIC_MODELS: { id: AnthropicModel; label: string; value: AnthropicModel }[] = [
  { id: 'claude-sonnet-4-20250514', label: 'Claude Sonnet 4', value: 'claude-sonnet-4-20250514' },
  { id: 'claude-opus-4-20250514', label: 'Claude Opus 4', value: 'claude-opus-4-20250514' },
  { id: 'claude-haiku-3-20250401', label: 'Claude Haiku 3', value: 'claude-haiku-3-20250401' },
];

export const GOOGLE_MODELS: { id: GoogleModel; label: string; value: GoogleModel }[] = [
  { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', value: 'gemini-2.5-flash' },
  { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', value: 'gemini-2.5-pro' },
  { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash', value: 'gemini-2.0-flash' },
];

// ── Inference mode feature flags (stub — will come from Rust) ────

export interface InferenceModeFeatures {
  canStream: boolean;
  canReason: boolean;
  canReroute: boolean;
  canSteer: boolean;
  /** Whether play/pause thinking controls are available */
  playPause: boolean;
  /** Short hint text about the current inference mode */
  modeHint: string;
  /** Display label for the current mode */
  modeLabel: string;
  /** Whether thinking can be rerouted to a different model */
  rerouteThinking: boolean;
}

export function getInferenceModeFeatures(mode: InferenceMode): InferenceModeFeatures {
  const isLocal = mode === 'local';
  return {
    canStream: true,
    canReason: true,
    canReroute: !isLocal,
    canSteer: true,
    playPause: isLocal,
    modeHint: isLocal ? 'Local inference' : 'Cloud API',
    modeLabel: isLocal ? 'Local' : 'Cloud',
    rerouteThinking: !isLocal,
  };
}
