/**
 * UI Display Types — thin type definitions for rendering data from Rust backend.
 *
 * These will eventually be auto-generated by tauri-specta from Rust structs.
 * For now they're minimal placeholders so the UI compiles.
 * ALL logic lives in Rust crates (ported from Mac version). TypeScript only renders.
 */

import type { PipelineStage, SafetyState } from '@/lib/constants';

// ── Pipeline Display ─────────────────────────────────────────────

export type StageStatus = 'idle' | 'active' | 'complete' | 'error';

export interface StageResult {
  stage: PipelineStage;
  status: StageStatus;
  summary: string;
  detail?: string;
  value?: number;
}

export interface TDASnapshot {
  betti0: number;
  betti1: number;
  persistenceEntropy: number;
  maxPersistence: number;
}

export interface SignalUpdate {
  confidence?: number;
  entropy?: number;
  dissonance?: number;
  healthScore?: number;
  safetyState?: SafetyState;
  riskScore?: number;
  tda?: Partial<TDASnapshot>;
  focusDepth?: number;
  temperatureScale?: number;
  activeConcepts?: string[];
  activeChordProduct?: number;
  harmonyKeyDistance?: number;
}

// ── Messages ─────────────────────────────────────────────────────

export type AnalysisMode = 'research' | 'quick' | 'deep';
export type EvidenceGrade = 'A' | 'B' | 'C' | 'D' | 'F' | 'N/A';

export interface LaymanSummary {
  whatIsLikelyTrue: string;
  whatIsUncertain: string;
  whatToWatch: string;
}

export interface DualMessage {
  rawAnalysis: string;
  laymanSummary?: LaymanSummary;
}

export interface TruthAssessment {
  overallTruthLikelihood: number;
  verdict: string;
  strengths: string[];
  weaknesses: string[];
  nuances: string[];
}

export interface FileAttachment {
  id: string;
  name: string;
  type: string;
  uri: string;
  size: number;
  mimeType?: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'system';
  text: string;
  timestamp: number;
  confidence?: number;
  evidenceGrade?: EvidenceGrade;
  mode?: AnalysisMode;
  dualMessage?: DualMessage;
  truthAssessment?: TruthAssessment;
  concepts?: string[];
  reasoning?: { content: string; duration?: number };
  attachments?: FileAttachment[];
}

// ── Pipeline Controls (UI sliders) ───────────────────────────────

export interface PipelineControls {
  focusDepthOverride: number | null;
  temperatureOverride: number | null;
  complexityBias: number;
  adversarialIntensity: number;
  bayesianPriorStrength: number;
}

// ── Inference Config (settings UI) ───────────────────────────────

export type InferenceMode = 'api' | 'local';
export type ApiProvider = 'openai' | 'anthropic' | 'google';

export type OpenAIModel = 'gpt-4o' | 'gpt-4o-mini' | 'o1' | 'o1-mini' | 'o3-mini';
export type AnthropicModel = 'claude-sonnet-4-20250514' | 'claude-opus-4-20250514' | 'claude-haiku-3-20250401';
export type GoogleModel = 'gemini-2.5-flash' | 'gemini-2.5-pro' | 'gemini-2.0-flash';

export interface InferenceConfig {
  mode: InferenceMode;
  apiProvider?: ApiProvider;
  apiKey?: string;
  openaiModel?: OpenAIModel;
  anthropicModel?: AnthropicModel;
  googleModel?: GoogleModel;
  ollamaBaseUrl?: string;
  ollamaModel?: string;
}

export interface OllamaHardwareStatus {
  gpuAvailable: boolean;
  gpuName?: string;
  vramMB?: number;
  systemMemoryMB?: number;
}

// ── Provider/Model lists for settings dropdowns ──────────────────

export const API_PROVIDERS: { id: ApiProvider; label: string }[] = [
  { id: 'openai', label: 'OpenAI' },
  { id: 'anthropic', label: 'Anthropic' },
  { id: 'google', label: 'Google' },
];

export const OPENAI_MODELS: { id: OpenAIModel; label: string }[] = [
  { id: 'gpt-4o', label: 'GPT-4o' },
  { id: 'gpt-4o-mini', label: 'GPT-4o Mini' },
  { id: 'o1', label: 'o1' },
  { id: 'o1-mini', label: 'o1 Mini' },
  { id: 'o3-mini', label: 'o3 Mini' },
];

export const ANTHROPIC_MODELS: { id: AnthropicModel; label: string }[] = [
  { id: 'claude-sonnet-4-20250514', label: 'Claude Sonnet 4' },
  { id: 'claude-opus-4-20250514', label: 'Claude Opus 4' },
  { id: 'claude-haiku-3-20250401', label: 'Claude Haiku 3' },
];

export const GOOGLE_MODELS: { id: GoogleModel; label: string }[] = [
  { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
  { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
  { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
];

// ── Inference mode feature flags (stub — will come from Rust) ────

export interface InferenceModeFeatures {
  canStream: boolean;
  canReason: boolean;
  canReroute: boolean;
  canSteer: boolean;
}

export function getInferenceModeFeatures(_mode: InferenceMode): InferenceModeFeatures {
  // All features enabled — Rust backend handles capability detection
  return { canStream: true, canReason: true, canReroute: true, canSteer: true };
}
