// Vault sync via Tauri commands — bridges the web-era Vault abstraction
// to the Rust backend's page/folder storage.

import { commands } from '@/lib/bindings';
import type { Page, Folder, Block } from '@/lib/bindings';
import type { Vault, NotePage, NoteBook, NoteBlock, PageLink, Concept, BlockType } from './types';
import { normalizePageName, generateBlockId, extractPageLinks, stripHtml } from './types';

// ── Type mappers (Tauri Page/Folder → store NotePage/NoteBook) ─────

function mapPageToNotePage(p: Page): NotePage {
  return {
    id: p.id,
    title: p.title,
    name: normalizePageName(p.title),
    isJournal: p.is_journal,
    journalDate: p.journal_date ?? undefined,
    icon: p.emoji ?? undefined,
    properties: {},
    tags: p.tags,
    favorite: p.is_favorite,
    pinned: p.is_pinned,
    createdAt: p.created_at,
    updatedAt: p.updated_at,
  };
}

function mapFolderToNoteBook(f: Folder): NoteBook {
  return {
    id: f.id,
    title: f.name,
    icon: f.emoji ?? undefined,
    pageIds: [],
    createdAt: f.created_at,
    updatedAt: f.created_at,
    autoGenerated: false,
    chapters: [],
    parentId: f.parent_folder_id,
  };
}

// ── Sync functions ─────────────────────────────────────────────────

const LOCAL_VAULT_ID = 'local';

export async function checkMigrationStatus(): Promise<boolean> {
  // Tauri always uses the SQLite backend as source of truth.
  return true;
}

export async function loadVaultsFromDb(): Promise<Vault[]> {
  // Single "Local" vault wrapping the Tauri backend
  const pagesRes = await commands.listPages();
  const pageCount = pagesRes.status === 'ok' ? pagesRes.data.length : 0;

  return [{
    id: LOCAL_VAULT_ID,
    name: 'Local',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    pageCount,
  }];
}

export async function loadVaultDataFromDb(_vaultId: string): Promise<{
  pages: NotePage[];
  blocks: NoteBlock[];
  books: NoteBook[];
  concepts: Concept[];
  pageLinks: PageLink[];
}> {
  const [pagesRes, foldersRes] = await Promise.all([
    commands.listPages(),
    commands.listFolders(),
  ]);

  const pages: NotePage[] = pagesRes.status === 'ok'
    ? pagesRes.data.map(mapPageToNotePage)
    : [];

  const books: NoteBook[] = foldersRes.status === 'ok'
    ? foldersRes.data.map(mapFolderToNoteBook)
    : [];

  // Assign pages to their folders (books)
  if (pagesRes.status === 'ok') {
    for (const p of pagesRes.data) {
      if (p.folder_id) {
        const book = books.find((b) => b.id === p.folder_id);
        if (book) book.pageIds.push(p.id);
      }
    }
  }

  return {
    pages,
    blocks: [],  // Blocks loaded per-page via loadBody
    books,
    concepts: [],
    pageLinks: [],
  };
}

export async function syncVaultToServer(_vaultId: string, ..._args: unknown[]): Promise<void> {
  // Per-page saves handled individually via commands.saveBody/updatePage
}

export async function migrateToSqlite(_payload?: unknown): Promise<{ ok: boolean; skipped: boolean }> {
  return { ok: true, skipped: true };
}

export async function upsertVaultOnServer(_vault: Vault): Promise<void> {
  // Vault metadata is implicit in Tauri — no separate upsert needed
}

export async function deleteVaultOnServer(_vaultId: string): Promise<void> {
  // Cannot delete the local vault
}

// ── Folder CRUD (Tauri backend persistence) ────────────────────────

export async function createFolderOnBackend(name: string): Promise<Folder | null> {
  const res = await commands.createFolder(name);
  return res.status === 'ok' ? res.data : null;
}

export async function deleteFolderOnBackend(folderId: string): Promise<void> {
  await commands.deleteFolder(folderId);
}

export async function updateFolderOnBackend(
  folderId: string,
  update: Partial<Folder>,
): Promise<void> {
  const foldersRes = await commands.listFolders();
  if (foldersRes.status !== 'ok') return;
  const folder = foldersRes.data.find((f) => f.id === folderId);
  if (!folder) return;
  await commands.updateFolder({ ...folder, ...update });
}

// ── Page CRUD (Tauri backend persistence) ──────────────────────────

export async function createPageOnBackend(title: string): Promise<Page | null> {
  const res = await commands.createPage(title);
  return res.status === 'ok' ? res.data : null;
}

export async function deletePageOnBackend(pageId: string): Promise<void> {
  await commands.deletePage(pageId);
}

export async function updatePageTitleOnBackend(pageId: string, newTitle: string): Promise<void> {
  const res = await commands.getPage(pageId);
  if (res.status !== 'ok') return;
  await commands.updatePage({ ...res.data, title: newTitle, updated_at: Date.now() });
}

export async function updatePageFieldOnBackend(
  pageId: string,
  update: Partial<Page>,
): Promise<void> {
  const res = await commands.getPage(pageId);
  if (res.status !== 'ok') return;
  await commands.updatePage({ ...res.data, ...update, updated_at: Date.now() });
}

// ── Block loading / body saving ────────────────────────────────────

function detectBlockType(
  content: string,
): { type: BlockType; content: string; properties: Record<string, string> } {
  const trimmed = content.trim();
  if (trimmed.startsWith('### '))
    return { type: 'heading', content: trimmed.slice(4), properties: { level: '3' } };
  if (trimmed.startsWith('## '))
    return { type: 'heading', content: trimmed.slice(3), properties: { level: '2' } };
  if (trimmed.startsWith('# '))
    return { type: 'heading', content: trimmed.slice(2), properties: { level: '1' } };
  if (trimmed.startsWith('> '))
    return { type: 'quote', content: trimmed.slice(2), properties: {} };
  if (/^- \[[ x]\] /.test(trimmed)) {
    const checked = trimmed.startsWith('- [x] ');
    return { type: 'todo', content: trimmed.slice(6), properties: { checked: String(checked) } };
  }
  if (trimmed.startsWith('- ') || trimmed.startsWith('* '))
    return { type: 'list-item', content: trimmed.slice(2), properties: {} };
  if (/^\d+\.\s/.test(trimmed))
    return { type: 'numbered-item', content: trimmed.replace(/^\d+\.\s/, ''), properties: {} };
  if (trimmed === '---' || trimmed === '***')
    return { type: 'divider', content: '', properties: {} };
  return { type: 'paragraph', content: trimmed, properties: {} };
}

function mapRustBlockToNoteBlock(b: Block): NoteBlock {
  const detected = detectBlockType(b.content);
  return {
    id: b.id,
    pageId: b.page_id,
    parentId: b.parent_block_id,
    order: String(b.order).padStart(4, '0'),
    indent: b.depth,
    content: detected.content,
    type: detected.type,
    collapsed: b.is_collapsed,
    refs: extractPageLinks(b.content),
    properties: detected.properties,
    createdAt: b.created_at,
    updatedAt: b.updated_at,
  };
}

export async function loadPageBlocks(pageId: string): Promise<NoteBlock[]> {
  // Try structured blocks first (Rust BlockParser output)
  const blocksRes = await commands.getBlocks(pageId);
  if (blocksRes.status === 'ok' && blocksRes.data.length > 0) {
    return blocksRes.data.map(mapRustBlockToNoteBlock);
  }

  // Fallback: load raw markdown body and split into blocks
  const bodyRes = await commands.loadBody(pageId);
  if (bodyRes.status === 'ok' && bodyRes.data.trim()) {
    const lines = bodyRes.data.split('\n');
    const blocks: NoteBlock[] = [];
    let orderIdx = 0;
    for (const line of lines) {
      if (line.trim() === '') continue;
      const detected = detectBlockType(line);
      blocks.push({
        id: generateBlockId(),
        pageId,
        parentId: null,
        order: String(orderIdx).padStart(4, '0'),
        indent: 0,
        content: detected.content,
        type: detected.type,
        collapsed: false,
        refs: extractPageLinks(line),
        properties: detected.properties,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      });
      orderIdx++;
    }
    return blocks;
  }

  return [];
}

function serializeBlockToMarkdown(block: NoteBlock): string {
  const content = stripHtml(block.content);
  switch (block.type) {
    case 'heading': {
      const level = parseInt(block.properties.level || '1', 10);
      return `${'#'.repeat(level)} ${content}`;
    }
    case 'quote': return `> ${content}`;
    case 'list-item': return `- ${content}`;
    case 'numbered-item': return `1. ${content}`;
    case 'todo': return `- [${block.properties.checked === 'true' ? 'x' : ' '}] ${content}`;
    case 'code': return `\`\`\`\n${content}\n\`\`\``;
    case 'divider': return '---';
    default: return content;
  }
}

export async function savePageBodyToBackend(
  pageId: string,
  blocks: NoteBlock[],
): Promise<void> {
  const pageBlocks = blocks
    .filter((b) => b.pageId === pageId)
    .sort((a, b) => a.order.localeCompare(b.order));
  const markdown = pageBlocks.map(serializeBlockToMarkdown).join('\n');
  await commands.saveBody(pageId, markdown);
}
